window.APEX = {
  races: [
    { id: "bhr", season: 2027, round: 1, country: "Bahrain", name: "Gulf Air Bahrain Grand Prix", circuit: "Bahrain International Circuit", dates: "12 – 14 Mar", raceDate: "2027-03-14", region: "middle-east", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 141 },
      { id: "main", name: "Main Grandstand", kind: "seat", price: 364 },
      { id: "club", name: "Paddock Club", kind: "club", price: 1960 },
      { id: "batelco", name: "Batelco", kind: "seat", price: 336 },
      { id: "turn1", name: "Turn1", kind: "seat", price: 238 },
      { id: "universitygs", name: "University gs", kind: "seat", price: 196 },
      { id: "victorygrandstand", name: "Victory grandstand", kind: "seat", price: 294 },
      { id: "viptent", name: "Vip tent", kind: "club", price: 1120 },
      { id: "thedome", name: "The Dome", kind: "seat", price: 686 },
      { id: "podiumview", name: "Podium view", kind: "seat", price: 504 },
      { id: "sectionpr", name: "Section p+r", kind: "seat", price: 252 },
    ] },
    { id: "sau", season: 2027, round: 2, country: "Saudi Arabia", name: "STC Saudi Arabian Grand Prix", circuit: "Jeddah Corniche Circuit", dates: "19 – 21 Mar", raceDate: "2027-03-21", region: "middle-east", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 95 },
      { id: "central", name: "Central Grandstand", kind: "seat", price: 181 },
      { id: "main", name: "Main Grandstand B", kind: "seat", price: 373 },
      { id: "paddockclub", name: "Paddock Club", kind: "club", price: 1680 },
      { id: "premiumhospitality", name: "Premium hospitality", kind: "club", price: 2240 },
    ] },
    { id: "aus", season: 2027, round: 3, country: "Australia", name: "Moët & Chandon Australian Grand Prix", circuit: "Albert Park Circuit", dates: "2 – 4 Apr", raceDate: "2027-04-04", region: "asia", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 189 },
      { id: "jones", name: "Jones Grandstand", kind: "seat", price: 290 },
      { id: "club", name: "Paddock Club", kind: "club", price: 1820 },
      { id: "thepalms", name: "THE PALMS", kind: "seat", price: 686 },
      { id: "thealbert", name: "The ALBERT", kind: "seat", price: 840 },
      { id: "theapex", name: "The Apex", kind: "seat", price: 1155 },
      { id: "racecube", name: "RaceCube", kind: "seat", price: 574 },
      { id: "theatrium", name: "The Atrium", kind: "seat", price: 980 },
    ] },
    { id: "jpn", season: 2027, round: 4, country: "Japan", name: "Lenovo Japanese Grand Prix", circuit: "Suzuka Circuit", dates: "9 – 11 Apr", raceDate: "2027-04-11", region: "asia", tickets: [
      { id: "a", name: "A Stand", kind: "seat", price: 448 },
      { id: "v2", name: "V2 Grandstand", kind: "seat", price: 697 },
      { id: "club", name: "Paddock Club", kind: "club", price: 1680 },
      { id: "ga", name: "General admission", kind: "seat", price: 108 },
      { id: "q2", name: "Q2", kind: "seat", price: 529 },
      { id: "q1", name: "Q1", kind: "seat", price: 476 },
      { id: "b1", name: "B1", kind: "seat", price: 420 },
      { id: "c", name: "Grandstand C", kind: "seat", price: 364 },
      { id: "e", name: "Grandstand E", kind: "seat", price: 211 },
      { id: "r", name: "Grandstand R", kind: "seat", price: 360 },
      { id: "s", name: "Grandstand S", kind: "seat", price: 301 },
      { id: "v1", name: "V1", kind: "seat", price: 577 },
      { id: "i", name: "Grandstand I", kind: "seat", price: 282 },
      { id: "p", name: "Grandstand P", kind: "seat", price: 169 },
      { id: "m", name: "Grandstand M", kind: "seat", price: 169 },
      { id: "d", name: "Grandstand D", kind: "seat", price: 190 },
      { id: "doasis", name: "D Oasis", kind: "seat", price: 233 },
      { id: "g", name: "Grandstand G", kind: "seat", price: 151 },
      { id: "o", name: "Grandstand O", kind: "seat", price: 132 },
      { id: "b2", name: "B2", kind: "seat", price: 449 },
      { id: "h", name: "Grandstand H", kind: "seat", price: 241 },
    ] },
    { id: "chn", season: 2027, round: 5, country: "China", name: "Heineken Chinese Grand Prix", circuit: "Shanghai International Circuit", dates: "16 – 18 Apr", raceDate: "2027-04-18", region: "asia", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 133 },
      { id: "main", name: "Main Grandstand", kind: "seat", price: 336 },
      { id: "club", name: "Paddock Club", kind: "club", price: 1960 },
      { id: "gashangai", name: "GA Shangai", kind: "seat", price: 133 },
      { id: "gs1234242", name: "Grandstand 1", kind: "seat", price: 182 },
      { id: "gs9965", name: "Grandstand 2", kind: "seat", price: 217 },
      { id: "gs8768689", name: "Grandstand 3", kind: "seat", price: 252 },
      { id: "gs2627362", name: "Grandstand 4", kind: "seat", price: 294 },
    ] },
    { id: "mia", season: 2027, round: 6, country: "Miami", name: "Hard Rock Miami Grand Prix", circuit: "Miami International Autodrome", dates: "30 Apr – 2 May", raceDate: "2027-05-02", region: "americas", tickets: [
      { id: "beach", name: "North Beach Grandstand", kind: "seat", price: 507 },
      { id: "t18", name: "Turn 18 Grandstand", kind: "seat", price: 847 },
      { id: "sf", name: "Start/Finish Grandstand", kind: "seat", price: 1232 },
      { id: "turn1", name: "Turn1", kind: "seat", price: 686 },
      { id: "beachsouth", name: "Beach South", kind: "seat", price: 483 },
      { id: "paddockclub", name: "Paddock Club", kind: "club", price: 4340 },
      { id: "marina", name: "Marina", kind: "seat", price: 602 },
      { id: "boathouse", name: "Boat House", kind: "seat", price: 1540 },
      { id: "miahospitalityvillagec", name: "MIA Hospitality Village & Club", kind: "club", price: 3360 },
    ] },
    { id: "can", season: 2027, round: 7, country: "Canada", name: "AWS Grand Prix du Canada", circuit: "Circuit Gilles-Villeneuve", dates: "21 – 23 May", raceDate: "2027-05-23", region: "americas", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 136 },
      { id: "gs12", name: "Grandstand 12", kind: "seat", price: 503 },
      { id: "club", name: "Paddock Club", kind: "club", price: 2520 },
      { id: "g16", name: "Grandstand 16", kind: "seat", price: 364 },
      { id: "family", name: "Family", kind: "seat", price: 294 },
      { id: "g32", name: "Grandstand 32", kind: "seat", price: 322 },
      { id: "eliterestaurant", name: "Elite Restaurant", kind: "seat", price: 623 },
      { id: "vipfanselitesuite", name: "VIP Fan’s Elite Suite", kind: "club", price: 1330 },
      { id: "sennaclub", name: "Senna Club", kind: "club", price: 1680 },
      { id: "g1978terrace", name: "1978 Terrace", kind: "seat", price: 826 },
      { id: "latoundra", name: "La Toundra", kind: "seat", price: 532 },
      { id: "privilege", name: "Privilege", kind: "seat", price: 686 },
      { id: "g31", name: "Grandstand 31", kind: "seat", price: 332 },
      { id: "g21", name: "Grandstand 21", kind: "seat", price: 419 },
      { id: "stroll", name: "Stroll", kind: "seat", price: 483 },
      { id: "g46", name: "Grandstand 46", kind: "seat", price: 251 },
      { id: "g34", name: "Grandstand 34", kind: "seat", price: 342 },
      { id: "main", name: "Main", kind: "seat", price: 686 },
      { id: "platinegs", name: "Platine GS", kind: "seat", price: 866 },
      { id: "g47", name: "Grandstand 47", kind: "seat", price: 241 },
      { id: "cgvterrace", name: "CGV terrace", kind: "seat", price: 504 },
      { id: "g1", name: "Grandstand 1", kind: "seat", price: 583 },
      { id: "cgvexperience", name: "CGV Experience", kind: "seat", price: 735 },
      { id: "privilege17", name: "Privilege 17", kind: "seat", price: 770 },
      { id: "lajamaque", name: "La Jamaïque", kind: "seat", price: 448 },
      { id: "terrace21", name: "Terrace 21", kind: "seat", price: 588 },
      { id: "cosmosclub", name: "Cosmos club", kind: "club", price: 1190 },
    ] },
    { id: "mon", season: 2027, round: 8, country: "Monaco", name: "Louis Vuitton Grand Prix de Monaco", circuit: "Circuit de Monaco", dates: "4 – 6 Jun", raceDate: "2027-06-06", region: "europe", tickets: [
      { id: "rocher", name: "Rocher", kind: "seat", price: 1043 },
      { id: "k", name: "Tribune K", kind: "seat", price: 1043 },
      { id: "club", name: "Paddock Club", kind: "club", price: 8680 },
      { id: "ga", name: "General admission", kind: "seat", price: 154 },
      { id: "romaitalianrivieraloun", name: "Roma Italian Riviera Lounge", kind: "club", price: 5460 },
      { id: "l", name: "Tribune L", kind: "seat", price: 826 },
      { id: "v1", name: "V1", kind: "seat", price: 945 },
      { id: "x2", name: "X2", kind: "seat", price: 994 },
      { id: "x1", name: "X1", kind: "seat", price: 1050 },
      { id: "b", name: "Tribune B", kind: "seat", price: 1254 },
      { id: "c", name: "Tribune C", kind: "seat", price: 980 },
      { id: "a1", name: "A1", kind: "seat", price: 875 },
      { id: "z1", name: "Z1", kind: "seat", price: 924 },
      { id: "m", name: "Tribune M", kind: "seat", price: 896 },
      { id: "n", name: "Tribune N", kind: "seat", price: 796 },
      { id: "e", name: "Tribune E", kind: "seat", price: 854 },
      { id: "p", name: "Tribune P", kind: "seat", price: 796 },
      { id: "t", name: "Tribune T", kind: "seat", price: 1043 },
      { id: "belvedere", name: "Belvedere", kind: "seat", price: 1120 },
      { id: "terraces", name: "Terraces", kind: "seat", price: 2415 },
      { id: "shangrila", name: "Shangri-la", kind: "seat", price: 3220 },
      { id: "albatros", name: "Albatros", kind: "seat", price: 2170 },
      { id: "hirondele", name: "Hirondele", kind: "seat", price: 2170 },
      { id: "panorama", name: "Panorama", kind: "seat", price: 2730 },
      { id: "caravelle", name: "Caravelle", kind: "seat", price: 2520 },
      { id: "trackside", name: "Trackside", kind: "seat", price: 2940 },
      { id: "ermano", name: "Ermano", kind: "seat", price: 1960 },
      { id: "heracles", name: "Heracles", kind: "seat", price: 3570 },
      { id: "panoramafanclub", name: "Panorama fan club", kind: "club", price: 3640 },
      { id: "bronze", name: "Bronze", kind: "seat", price: 1288 },
      { id: "platiniumheracles", name: "Platinium heracles", kind: "seat", price: 6440 },
      { id: "silver", name: "Silver", kind: "seat", price: 2415 },
      { id: "platinium", name: "Platinium", kind: "seat", price: 5950 },
      { id: "gold", name: "Gold", kind: "seat", price: 4186 },
      { id: "gs23898", name: "Grandstand 1", kind: "seat", price: 796 },
      { id: "gs11967", name: "Grandstand 2", kind: "seat", price: 854 },
    ] },
    { id: "por", season: 2027, round: 9, country: "Portugal", name: "MSC Cruises Grande Prémio de Portugal", circuit: "Autódromo Internacional do Algarve", dates: "18 – 20 Jun", raceDate: "2027-06-20", region: "europe", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 122 },
      { id: "main", name: "Main Grandstand", kind: "seat", price: 294 },
      { id: "club", name: "Hospitality", kind: "club", price: 1540 },
    ] },
    { id: "gbr", season: 2027, round: 10, country: "Great Britain", name: "TAG Heuer British Grand Prix", circuit: "Silverstone", dates: "2 – 4 Jul", raceDate: "2027-07-04", region: "europe", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 218 },
      { id: "chapel", name: "Chapel Grandstand", kind: "seat", price: 372 },
      { id: "hamilton", name: "Hamilton Straight A", kind: "seat", price: 592 },
      { id: "gasilverstone", name: "GA Silverstone", kind: "seat", price: 218 },
      { id: "redbullpoleposition", name: "Red bull pole position", kind: "seat", price: 568 },
      { id: "gs25308", name: "Grandstand 1", kind: "seat", price: 372 },
      { id: "gs25318", name: "Grandstand 2", kind: "seat", price: 397 },
      { id: "gs25328", name: "Grandstand 3", kind: "seat", price: 413 },
      { id: "gs25338", name: "Grandstand 4", kind: "seat", price: 421 },
      { id: "gs25348", name: "Grandstand 5", kind: "seat", price: 438 },
      { id: "gs27179", name: "Grandstand 6", kind: "seat", price: 446 },
      { id: "gs27239", name: "Grandstand 7", kind: "seat", price: 470 },
      { id: "gs27279", name: "Grandstand 8", kind: "seat", price: 478 },
      { id: "gs27289", name: "Grandstand 9", kind: "seat", price: 486 },
      { id: "gs27299", name: "Grandstand 10", kind: "seat", price: 494 },
      { id: "gs27309", name: "Grandstand 11", kind: "seat", price: 503 },
      { id: "gs27319", name: "Grandstand 12", kind: "seat", price: 511 },
      { id: "gs27329", name: "Grandstand 13", kind: "seat", price: 519 },
      { id: "gs8205", name: "Grandstand 14", kind: "seat", price: 527 },
      { id: "gs8225", name: "Grandstand 15", kind: "seat", price: 543 },
      { id: "gs8265", name: "Grandstand 16", kind: "seat", price: 552 },
      { id: "gs8275", name: "Grandstand 17", kind: "seat", price: 592 },
      { id: "gs8285", name: "Grandstand 18", kind: "seat", price: 616 },
      { id: "gs8315", name: "Grandstand 19", kind: "seat", price: 372 },
      { id: "gs8325", name: "Grandstand 20", kind: "seat", price: 397 },
      { id: "gs8365", name: "Grandstand 21", kind: "seat", price: 413 },
      { id: "gs8385", name: "Grandstand 22", kind: "seat", price: 421 },
      { id: "gs8395", name: "Grandstand 23", kind: "seat", price: 438 },
      { id: "gs8405", name: "Grandstand 24", kind: "seat", price: 446 },
      { id: "gs8415", name: "Grandstand 25", kind: "seat", price: 470 },
    ] },
    { id: "aut", season: 2027, round: 11, country: "Austria", name: "Qatar Airways Austrian Grand Prix", circuit: "Red Bull Ring", dates: "9 – 11 Jul", raceDate: "2027-07-11", region: "europe", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 104 },
      { id: "jk", name: "Red Bull J/K", kind: "seat", price: 230 },
      { id: "sz", name: "Start-Ziel", kind: "seat", price: 384 },
      { id: "gs17417", name: "Grandstand 1", kind: "seat", price: 132 },
      { id: "gs9375", name: "Grandstand 2", kind: "seat", price: 160 },
      { id: "gs9345", name: "Grandstand 3", kind: "seat", price: 188 },
      { id: "gs9315", name: "Grandstand 4", kind: "seat", price: 216 },
      { id: "gs9325", name: "Grandstand 5", kind: "seat", price: 244 },
      { id: "gs9335", name: "Grandstand 6", kind: "seat", price: 272 },
    ] },
    { id: "bel", season: 2027, round: 12, country: "Belgium", name: "MSC Cruises Belgian Grand Prix", circuit: "Circuit de Spa-Francorchamps", dates: "23 – 25 Jul", raceDate: "2027-07-25", region: "europe", tickets: [
      { id: "ga", name: "Bronze General admission", kind: "seat", price: 150 },
      { id: "gs", name: "17–27 Grandstand", kind: "seat", price: 182 },
      { id: "gold", name: "Gold 1 Grandstand", kind: "seat", price: 598 },
      { id: "paddockclub", name: "Paddock club", kind: "club", price: 1680 },
      { id: "logedome", name: "Loge dome", kind: "seat", price: 1260 },
      { id: "sourceofgold", name: "Source of Gold", kind: "seat", price: 626 },
      { id: "mezzanine", name: "Mezzanine", kind: "seat", price: 504 },
      { id: "gold6", name: "Gold6", kind: "seat", price: 382 },
      { id: "gold9bis", name: "Gold9bis", kind: "seat", price: 444 },
      { id: "gold9", name: "Gold9", kind: "seat", price: 493 },
      { id: "gold8", name: "Gold8", kind: "seat", price: 545 },
      { id: "gold7", name: "Gold7", kind: "seat", price: 475 },
      { id: "gold7ter", name: "Gold7ter", kind: "seat", price: 405 },
      { id: "silver2", name: "Silver2", kind: "seat", price: 322 },
      { id: "gold2", name: "Gold2", kind: "seat", price: 572 },
      { id: "silver1", name: "Silver1", kind: "seat", price: 346 },
      { id: "gold4", name: "Gold4", kind: "seat", price: 662 },
      { id: "gold3", name: "Gold3", kind: "seat", price: 692 },
      { id: "silver4", name: "Silver4", kind: "seat", price: 346 },
      { id: "combes1", name: "Combes 1", kind: "seat", price: 346 },
      { id: "combes2", name: "Combes 2", kind: "seat", price: 276 },
      { id: "combes3", name: "Combes 3", kind: "seat", price: 276 },
      { id: "combes4", name: "Combes 4", kind: "seat", price: 346 },
      { id: "silver7", name: "Silver7", kind: "seat", price: 315 },
      { id: "gold5", name: "Gold5", kind: "seat", price: 518 },
      { id: "silver3", name: "Silver3", kind: "seat", price: 354 },
      { id: "silver6", name: "Silver6", kind: "seat", price: 343 },
      { id: "speedcorner", name: "Speedcorner", kind: "seat", price: 266 },
      { id: "orange", name: "Orange", kind: "seat", price: 217 },
      { id: "fanareadoublegauche", name: "Fan Area (Double Gauche)", kind: "seat", price: 217 },
      { id: "gs25258", name: "Grandstand 1", kind: "seat", price: 217 },
      { id: "gs10385", name: "Grandstand 2", kind: "seat", price: 245 },
      { id: "gs26809", name: "Grandstand 3", kind: "seat", price: 266 },
      { id: "gs10375", name: "Grandstand 4", kind: "seat", price: 276 },
      { id: "gs10395", name: "Grandstand 5", kind: "seat", price: 315 },
    ] },
    { id: "hun", season: 2027, round: 13, country: "Hungary", name: "Aramco Hungarian Grand Prix", circuit: "Hungaroring", dates: "30 Jul – 1 Aug", raceDate: "2027-08-01", region: "europe", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 146 },
      { id: "chicane", name: "Chicane Grandstand", kind: "seat", price: 205 },
      { id: "plat", name: "Hungaroring Platinum", kind: "seat", price: 633 },
      { id: "silver5", name: "Silver5", kind: "seat", price: 175 },
      { id: "bronze1", name: "Bronze1", kind: "seat", price: 161 },
      { id: "bronze2", name: "Bronze2", kind: "seat", price: 172 },
      { id: "redbull", name: "Redbull", kind: "seat", price: 294 },
      { id: "silver4", name: "Silver4", kind: "seat", price: 196 },
      { id: "fanlounge", name: "Fan Lounge", kind: "club", price: 392 },
      { id: "gs24228", name: "Grandstand 1", kind: "seat", price: 161 },
      { id: "gs9215", name: "Grandstand 2", kind: "seat", price: 175 },
      { id: "gs9205", name: "Grandstand 3", kind: "seat", price: 196 },
      { id: "gs24958", name: "Grandstand 4", kind: "seat", price: 217 },
      { id: "gs24198", name: "Grandstand 5", kind: "seat", price: 238 },
      { id: "gs24208", name: "Grandstand 6", kind: "seat", price: 266 },
      { id: "gs24938", name: "Grandstand 7", kind: "seat", price: 294 },
      { id: "gs24218", name: "Grandstand 8", kind: "seat", price: 161 },
      { id: "gs24948", name: "Grandstand 9", kind: "seat", price: 175 },
    ] },
    { id: "ita", season: 2027, round: 14, country: "Italy", name: "Pirelli Gran Premio d'Italia", circuit: "Autodromo Nazionale Monza", dates: "3 – 5 Sep", raceDate: "2027-09-05", region: "europe", tickets: [
      { id: "para", name: "Laterale Parabolica D", kind: "seat", price: 271 },
      { id: "ascari", name: "Ascari Grandstand", kind: "seat", price: 271 },
      { id: "centrale", name: "Centrale Grandstand", kind: "seat", price: 271 },
      { id: "ultimatehospitality", name: "Ultimate Hospitality", kind: "club", price: 2240 },
      { id: "greenhouse", name: "Green house", kind: "seat", price: 623 },
      { id: "dolcevitalounge", name: "Dolce vita lounge", kind: "club", price: 980 },
      { id: "gs22438", name: "Grandstand 1", kind: "seat", price: 147 },
      { id: "gs26679", name: "Grandstand 2", kind: "seat", price: 175 },
      { id: "gs27819", name: "Grandstand 3", kind: "seat", price: 216 },
      { id: "gs29209", name: "Grandstand 4", kind: "seat", price: 243 },
      { id: "gs8955", name: "Grandstand 5", kind: "seat", price: 271 },
      { id: "gs8715", name: "Grandstand 6", kind: "seat", price: 301 },
      { id: "gs8705", name: "Grandstand 7", kind: "seat", price: 329 },
      { id: "gs18677", name: "Grandstand 8", kind: "seat", price: 147 },
      { id: "gs8805", name: "Grandstand 9", kind: "seat", price: 175 },
      { id: "gs8815", name: "Grandstand 10", kind: "seat", price: 216 },
      { id: "gs8825", name: "Grandstand 11", kind: "seat", price: 243 },
      { id: "gs8835", name: "Grandstand 12", kind: "seat", price: 271 },
      { id: "gs8935", name: "Grandstand 13", kind: "seat", price: 301 },
      { id: "gs27129", name: "Grandstand 14", kind: "seat", price: 329 },
      { id: "gs8725", name: "Grandstand 15", kind: "seat", price: 147 },
      { id: "gs8745", name: "Grandstand 16", kind: "seat", price: 175 },
      { id: "gs8755", name: "Grandstand 17", kind: "seat", price: 216 },
      { id: "gs8765", name: "Grandstand 18", kind: "seat", price: 243 },
      { id: "gs8775", name: "Grandstand 19", kind: "seat", price: 271 },
      { id: "gs8675", name: "Grandstand 20", kind: "seat", price: 301 },
      { id: "gs8665", name: "Grandstand 21", kind: "seat", price: 329 },
      { id: "gs8655", name: "Grandstand 22", kind: "seat", price: 147 },
      { id: "gs14147", name: "Grandstand 23", kind: "seat", price: 175 },
      { id: "gs12324324", name: "Grandstand 24", kind: "seat", price: 216 },
      { id: "gs28909", name: "Grandstand 25", kind: "seat", price: 243 },
      { id: "gs28919", name: "Grandstand 26", kind: "seat", price: 271 },
      { id: "gs3546645", name: "Grandstand 27", kind: "seat", price: 301 },
      { id: "gs8925", name: "Grandstand 28", kind: "seat", price: 329 },
      { id: "gs18567", name: "Grandstand 29", kind: "seat", price: 147 },
      { id: "gs8615", name: "Grandstand 30", kind: "seat", price: 175 },
      { id: "gs8645", name: "Grandstand 31", kind: "seat", price: 216 },
      { id: "gs8695", name: "Grandstand 32", kind: "seat", price: 243 },
      { id: "gs8885", name: "Grandstand 33", kind: "seat", price: 271 },
      { id: "gs8895", name: "Grandstand 34", kind: "seat", price: 301 },
      { id: "gs8905", name: "Grandstand 35", kind: "seat", price: 329 },
      { id: "gs8915", name: "Grandstand 36", kind: "seat", price: 147 },
      { id: "gs8635", name: "Grandstand 37", kind: "seat", price: 175 },
      { id: "gs8685", name: "Grandstand 38", kind: "seat", price: 216 },
    ] },
    { id: "esp", season: 2027, round: 15, country: "Spain", name: "Lenovo Gran Premio de España", circuit: "Madring Circuit", dates: "10 – 12 Sep", raceDate: "2027-09-12", region: "europe", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 126 },
      { id: "main", name: "Main Grandstand", kind: "seat", price: 294 },
      { id: "club", name: "Paddock Club", kind: "club", price: 1680 },
      { id: "gs27199", name: "Grandstand 1", kind: "seat", price: 168 },
      { id: "gs27209", name: "Grandstand 2", kind: "seat", price: 210 },
      { id: "gs29579", name: "Grandstand 3", kind: "seat", price: 252 },
    ] },
    { id: "aze", season: 2027, round: 16, country: "Azerbaijan", name: "Qatar Airways Azerbaijan Grand Prix", circuit: "Baku City Circuit", dates: "24 – 26 Sep", raceDate: "2027-09-26", region: "europe", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 115 },
      { id: "absheron", name: "Absheron Grandstand", kind: "seat", price: 357 },
      { id: "club", name: "Paddock Club", kind: "club", price: 1960 },
      { id: "champions", name: "Champions", kind: "seat", price: 1260 },
      { id: "khazar", name: "Khazar", kind: "seat", price: 266 },
      { id: "bulvar", name: "Bulvar", kind: "seat", price: 294 },
      { id: "sahil", name: "Sahil", kind: "seat", price: 315 },
      { id: "mugham", name: "Mugham", kind: "seat", price: 273 },
      { id: "gizgalasi", name: "Giz galasi", kind: "seat", price: 329 },
      { id: "icherisheher", name: "Icheri sheher", kind: "seat", price: 308 },
      { id: "azneft", name: "Azneft", kind: "seat", price: 252 },
      { id: "filarmoniya", name: "Filarmoniya", kind: "seat", price: 280 },
      { id: "marineloungeexperience", name: "Marine Lounge Experience", kind: "club", price: 1120 },
      { id: "marinegrandstand", name: "Marine Grandstand", kind: "seat", price: 434 },
      { id: "gs25848", name: "Grandstand 1", kind: "seat", price: 238 },
    ] },
    { id: "tur", season: 2027, round: 17, country: "Türkiye", name: "MSC Cruises Turkish Grand Prix", circuit: "TOSFED Istanbul Park", dates: "1 – 3 Oct", raceDate: "2027-10-03", region: "europe", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 105 },
      { id: "gs7", name: "Grandstand 7", kind: "seat", price: 238 },
      { id: "club", name: "Paddock Club", kind: "club", price: 1330 },
    ] },
    { id: "sgp", season: 2027, round: 18, country: "Singapore", name: "Singapore Airlines Singapore Grand Prix", circuit: "Marina Bay Street Circuit", dates: "8 – 10 Oct", raceDate: "2027-10-10", region: "asia", tickets: [
      { id: "walk", name: "Walkabout", kind: "seat", price: 304 },
      { id: "bay", name: "Bay Grandstand", kind: "seat", price: 613 },
      { id: "club", name: "Champions Club", kind: "club", price: 2940 },
      { id: "zone4", name: "Zone4", kind: "seat", price: 185 },
      { id: "zone3", name: "Zone3", kind: "seat", price: 200 },
      { id: "zone2", name: "Zone2", kind: "seat", price: 214 },
      { id: "zone1", name: "Zone1", kind: "seat", price: 238 },
      { id: "lougeturn3", name: "Louge-turn3", kind: "seat", price: 1260 },
      { id: "skysuite", name: "Skysuite", kind: "club", price: 2520 },
      { id: "greenroom", name: "GreenRoom", kind: "seat", price: 1680 },
      { id: "observ3", name: "Observ 3", kind: "seat", price: 1120 },
      { id: "twenty3", name: "Twenty3", kind: "seat", price: 1470 },
      { id: "pitexit", name: "Pit Exit", kind: "seat", price: 713 },
      { id: "promenade", name: "Promenade", kind: "seat", price: 613 },
      { id: "pit", name: "Pit", kind: "seat", price: 737 },
      { id: "superpitgs", name: "SuperPit GS", kind: "seat", price: 1042 },
      { id: "stamford", name: "Stamford", kind: "seat", price: 261 },
      { id: "connaught", name: "Connaught", kind: "seat", price: 318 },
      { id: "padang", name: "Padang", kind: "seat", price: 318 },
      { id: "empress", name: "Empress", kind: "seat", price: 318 },
      { id: "turn2", name: "Turn2", kind: "seat", price: 737 },
      { id: "turn1", name: "Turn1", kind: "seat", price: 737 },
      { id: "republicgrandstand", name: "Republic Grandstand", kind: "seat", price: 423 },
      { id: "rafles", name: "Rafles", kind: "seat", price: 523 },
      { id: "paulanerbruhaus", name: "PAULANER Bräuhaus", kind: "seat", price: 980 },
      { id: "dirversrightlounge", name: "Driver's right lounge", kind: "club", price: 1820 },
      { id: "skyline", name: "Skyline", kind: "seat", price: 1330 },
    ] },
    { id: "usa", season: 2027, round: 19, country: "United States", name: "Pirelli United States Grand Prix", circuit: "Circuit of the Americas", dates: "22 – 24 Oct", raceDate: "2027-10-24", region: "americas", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 192 },
      { id: "t15", name: "Turn 15 Grandstand", kind: "seat", price: 910 },
      { id: "club", name: "Paddock Club", kind: "club", price: 2940 },
      { id: "clubsi", name: "Club Si", kind: "club", price: 1960 },
      { id: "theterrace", name: "The terrace", kind: "seat", price: 1260 },
      { id: "plazaclub", name: "Plaza Club", kind: "club", price: 1680 },
      { id: "turn9", name: "Turn9", kind: "seat", price: 580 },
      { id: "turn4", name: "Turn4", kind: "seat", price: 554 },
      { id: "turn6", name: "Turn6", kind: "seat", price: 541 },
      { id: "turn2", name: "Turn2", kind: "seat", price: 567 },
      { id: "main", name: "Main", kind: "seat", price: 1308 },
      { id: "turn12", name: "Turn12", kind: "seat", price: 545 },
      { id: "turn13cabanas", name: "Turn13 Cabanas", kind: "seat", price: 1120 },
      { id: "turn1", name: "Turn1", kind: "seat", price: 708 },
      { id: "pf", name: "P F", kind: "seat", price: 490 },
      { id: "turn19", name: "Turn19", kind: "seat", price: 528 },
      { id: "pt", name: "P T", kind: "seat", price: 490 },
    ] },
    { id: "mex", season: 2027, round: 20, country: "Mexico", name: "Gran Premio de la Ciudad de México", circuit: "Autódromo Hermanos Rodríguez", dates: "29 – 31 Oct", raceDate: "2027-10-31", region: "americas", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 141 },
      { id: "foro", name: "Foro Sol", kind: "seat", price: 309 },
      { id: "club", name: "Paddock Club", kind: "club", price: 1960 },
      { id: "skyview", name: "Skyview", kind: "seat", price: 181 },
      { id: "tracksideboxes", name: "Trackside boxes", kind: "seat", price: 219 },
      { id: "tracksideboxc", name: "Trackside boxC", kind: "seat", price: 251 },
      { id: "skyboxg9", name: "Skybox G9", kind: "club", price: 290 },
      { id: "skyboxg10", name: "Skybox G10", kind: "club", price: 335 },
      { id: "skyboxg11", name: "Skybox G11", kind: "club", price: 374 },
      { id: "skyboxg1", name: "Skybox g1", kind: "club", price: 419 },
      { id: "speedloungegreen", name: "Speed lounge green", kind: "club", price: 181 },
      { id: "speedloungeyellow", name: "Speed lounge yellow", kind: "club", price: 219 },
      { id: "platiniumplus", name: "Platinium Plus", kind: "seat", price: 251 },
      { id: "g11", name: "Grandstand 11", kind: "seat", price: 290 },
      { id: "g6a", name: "Grandstand 6A", kind: "seat", price: 335 },
      { id: "g7", name: "Grandstand 7", kind: "seat", price: 374 },
      { id: "g8", name: "Grandstand 8", kind: "seat", price: 419 },
      { id: "g9", name: "Grandstand 9", kind: "seat", price: 181 },
      { id: "g6", name: "Grandstand 6", kind: "seat", price: 219 },
      { id: "g5", name: "Grandstand 5", kind: "seat", price: 251 },
      { id: "g5a", name: "Grandstand 5A", kind: "seat", price: 290 },
      { id: "g4", name: "Grandstand 4", kind: "seat", price: 335 },
      { id: "g3", name: "Grandstand 3", kind: "seat", price: 374 },
      { id: "g3a", name: "Grandstand 3A", kind: "seat", price: 419 },
      { id: "g10", name: "Grandstand 10", kind: "seat", price: 181 },
      { id: "terrazza", name: "Terrazza", kind: "seat", price: 219 },
    ] },
    { id: "bra", season: 2027, round: 21, country: "Brazil", name: "Heineken Grande Prêmio de São Paulo", circuit: "Autódromo José Carlos Pace", dates: "5 – 7 Nov", raceDate: "2027-11-07", region: "americas", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 122 },
      { id: "a", name: "Arquibancada A", kind: "seat", price: 270 },
      { id: "club", name: "Paddock Club", kind: "club", price: 1820 },
      { id: "orangetreeclub", name: "OrangeTreeClub", kind: "club", price: 1050 },
      { id: "grandprixclub", name: "GrandPrixClub", kind: "club", price: 1260 },
      { id: "pitstopclub", name: "PitStopClub", kind: "club", price: 1190 },
      { id: "g", name: "Grandstand G", kind: "seat", price: 155 },
      { id: "m", name: "Grandstand M", kind: "seat", price: 187 },
      { id: "b", name: "Grandstand B", kind: "seat", price: 219 },
      { id: "heineken", name: "Heineken", kind: "seat", price: 490 },
      { id: "r", name: "Grandstand R", kind: "seat", price: 251 },
      { id: "n", name: "Grandstand N", kind: "seat", price: 290 },
      { id: "d", name: "Grandstand D", kind: "seat", price: 335 },
      { id: "h", name: "Grandstand H", kind: "seat", price: 155 },
      { id: "v", name: "Grandstand V", kind: "seat", price: 187 },
      { id: "premiums", name: "PremiumS", kind: "seat", price: 840 },
    ] },
    { id: "lvg", season: 2027, round: 22, country: "Las Vegas", name: "Heineken Las Vegas Grand Prix", circuit: "Las Vegas Strip Circuit", dates: "18 – 20 Nov", raceDate: "2027-11-20", region: "americas", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 546 },
      { id: "sphere", name: "Sphere Grandstand", kind: "seat", price: 1155 },
      { id: "club", name: "Paddock Club", kind: "club", price: 5040 },
      { id: "gs23388", name: "Grandstand 1", kind: "seat", price: 686 },
      { id: "gs13232323", name: "Grandstand 2", kind: "seat", price: 840 },
      { id: "gs26449", name: "Grandstand 3", kind: "seat", price: 1015 },
      { id: "gs2222222", name: "Grandstand 4", kind: "seat", price: 1176 },
      { id: "gs26439", name: "Grandstand 5", kind: "seat", price: 1330 },
      { id: "gs23398", name: "Grandstand 6", kind: "seat", price: 686 },
    ] },
    { id: "qat", season: 2027, round: 23, country: "Qatar", name: "Qatar Airways Qatar Grand Prix", circuit: "Lusail International Circuit", dates: "3 – 5 Dec", raceDate: "2027-12-05", region: "middle-east", tickets: [
      { id: "club", name: "Champions Club", kind: "club", price: 4307 },
      { id: "hill", name: "Lusail Hill", kind: "seat", price: 2366 },
      { id: "main", name: "Main Grandstand", kind: "seat", price: 400 },
      { id: "north", name: "North Grandstand", kind: "seat", price: 300 },
      { id: "t16", name: "T16 Grandstand", kind: "seat", price: 200 },
      { id: "t2", name: "T2 Grandstand", kind: "seat", price: 244 },
      { id: "t3", name: "T3 Grandstand", kind: "seat", price: 272 },
      { id: "premirehospitality", name: "Première hospitality", kind: "club", price: 1540 },
      { id: "lusaillounge", name: "Lusail lounge", kind: "club", price: 1120 },
      { id: "paddockclub", name: "Paddock Club", kind: "club", price: 2940 },
      { id: "gs25138", name: "Grandstand 1", kind: "seat", price: 224 },
    ] },
    { id: "abu", season: 2027, round: 24, country: "Abu Dhabi", name: "Etihad Airways Abu Dhabi Grand Prix", circuit: "Yas Marina Circuit", dates: "10 – 12 Dec", raceDate: "2027-12-12", region: "middle-east", tickets: [
      { id: "ga", name: "General admission", kind: "seat", price: 297 },
      { id: "north", name: "North Grandstand", kind: "seat", price: 454 },
      { id: "club", name: "Yas Club", kind: "club", price: 647 },
      { id: "g36016", name: "360 16", kind: "seat", price: 385 },
      { id: "gardenonyas", name: "Garden on yas", kind: "seat", price: 315 },
      { id: "shamssuite", name: "Shams suite", kind: "club", price: 700 },
      { id: "marinaviewssuite", name: "Marina Views Suite", kind: "club", price: 735 },
      { id: "southclub", name: "South Club", kind: "club", price: 542 },
      { id: "deck9", name: "Deck 9", kind: "seat", price: 420 },
      { id: "deck2", name: "Deck 2", kind: "seat", price: 368 },
      { id: "turnwest", name: "Turn west", kind: "seat", price: 385 },
      { id: "lunalounge", name: "Luna lounge", kind: "club", price: 490 },
      { id: "sunsetlounge", name: "Sunset lounge", kind: "club", price: 455 },
      { id: "mainyassuitepremium", name: "Main Yas Suite Premium", kind: "club", price: 881 },
      { id: "sunsetgarage", name: "Sunset garage", kind: "seat", price: 350 },
      { id: "northstraight", name: "North Straight", kind: "seat", price: 332 },
      { id: "yassuitewest", name: "Yas Suite West", kind: "club", price: 822 },
      { id: "yassuitenorth", name: "Yas Suite North", kind: "club", price: 752 },
      { id: "yassuitemain", name: "Yas Suite Main", kind: "club", price: 788 },
      { id: "g360sixteen", name: "360 Sixteen", kind: "seat", price: 385 },
      { id: "marinags", name: "Marina GS", kind: "seat", price: 419 },
      { id: "westgs", name: "West GS", kind: "seat", price: 524 },
      { id: "weststraightgs", name: "West Straight GS", kind: "seat", price: 402 },
      { id: "southgs", name: "South GS", kind: "seat", price: 437 },
      { id: "maings", name: "Main GS", kind: "seat", price: 612 },
      { id: "club58", name: "Club58", kind: "club", price: 560 },
    ] },
  ],
  drivers: [
    { pos: 1, name: "Oscar Piastri", team: "McLaren", color: "#ff8700", pts: 318 },
    { pos: 2, name: "Lando Norris", team: "McLaren", color: "#ff8700", pts: 296 },
    { pos: 3, name: "Max Verstappen", team: "Red Bull", color: "#1414dc", pts: 271 },
    { pos: 4, name: "Charles Leclerc", team: "Ferrari", color: "#dc0000", pts: 248 },
    { pos: 5, name: "George Russell", team: "Mercedes", color: "#00d2be", pts: 221 },
    { pos: 6, name: "Lewis Hamilton", team: "Ferrari", color: "#dc0000", pts: 209 },
    { pos: 7, name: "Carlos Sainz", team: "Williams", color: "#00b2e3", pts: 164 },
    { pos: 8, name: "Kimi Antonelli", team: "Mercedes", color: "#00d2be", pts: 151 },
    { pos: 9, name: "Fernando Alonso", team: "Aston Martin", color: "#2b704c", pts: 98 },
    { pos: 10, name: "Alex Albon", team: "Williams", color: "#00b2e3", pts: 87 },
  ],
  teams: [
    { pos: 1, name: "McLaren", color: "#ff8700", pts: 614 },
    { pos: 2, name: "Ferrari", color: "#dc0000", pts: 457 },
    { pos: 3, name: "Red Bull", color: "#1414dc", pts: 402 },
    { pos: 4, name: "Mercedes", color: "#00d2be", pts: 372 },
    { pos: 5, name: "Williams", color: "#00b2e3", pts: 251 },
    { pos: 6, name: "Aston Martin", color: "#2b704c", pts: 168 },
    { pos: 7, name: "Racing Bulls", color: "#2864dc", pts: 142 },
    { pos: 8, name: "Haas", color: "#5a5a5a", pts: 96 },
    { pos: 9, name: "Alpine", color: "#f596c8", pts: 74 },
    { pos: 10, name: "Audi", color: "#e10600", pts: 61 },
    { pos: 11, name: "Cadillac", color: "#38383f", pts: 28 },
  ],
};
